import os
import time

for i in range(1, 10):

	os.system('cls')
	print(" ")
	print(" ")
	print("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+")
	print("    |    o             .     `          *                     |")
	print("    |            .          .                `       .        |")
	print("    |      o          .               *                       |")
	print("    |           .             .       `                 .     |")
	print("    |        .          o                .         *          |")
	print("    |*              o                                         |")
	print("    |     .   (•_•)/      `             *             .       |")
	print("    |        <)   )   IT'S                                    |")
	print("    |    .   /    \            *                          .   |")
	print("    |    o             .     `          *                     |")
	print("    |            .          .                `       .        |")
	print("    +---------------------------------------------------------+")
	print("    ", 10 - i, " more cylces")

	time.sleep(.900)
	
	os.system('cls')
	print(" ")
	print(" ")
	print("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+")
	print("    |            .          .                `       .        |")
	print("    |    o             .     `          *                     |")
	print("    |            .          .                `       .        |")
	print("    |      o          .               *                       |")
	print("    |           .             .       `                 .     |")
	print("    |        .          o                .         *          |")
	print("    |         (•_•)/                                          |")
	print("    |     .  <)   )   IT'S `               *            .     |")
	print("    |        /    \                                           |")
	print("    |    o             .     `   *                       .    |")
	print("    |*              o                    *                    |")
	print("    +---------------------------------------------------------+")
	print("    ", 10 - i, " more cylces")
	
	time.sleep(.800)
	
	os.system('cls')
	print(" ")
	print(" ")
	print("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+")
	print("    |           `         *                    ,     .        |")
	print("    |     o             .     `          *                    |")
	print("    |             .          .                `       .       |")
	print("    |       o          .               *                      |")
	print("    |            .             .       `                 .    |")
	print("    |       .            o                .         *         |")
	print("    |         \(•_•)      `             *             .       |")
	print("    |  *   .  (   (>  #BADGERS         *                .     |")
	print("    |         /    \                                          |")
	print("    |       o          .               *                      |")
	print("    |            .             .       `                 .    |")
	print("    +---------------------------------------------------------+")
	print("    ", 10 - i, " more cylces")
	
	time.sleep(.900)

	os.system('cls')
	print(" ")
	print(" ")
	print("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+")
	print("    |            .             .       `                 .    |")
	print("    |           `         *                    ,     .        |")
	print("    |     o             .     `          *                    |")
	print("    |             .          .                `       .       |")
	print("    |       o          .               *                      |")
	print("    |            .             .       `                 .    |")
	print("    |         \(•_•)                                          |")
	print("    |         (   (>  #BADGERS          *            .        |")
	print("    |    .    /    \        `          *                  .   |")
	print("    | *     .            o                .         *         |")	
	print("    |       o          .               *                      |")
	print("    +---------------------------------------------------------+")
	print("    ", 10 - i, " more cylces")
	
	time.sleep(.800)
	
	os.system('cls')
	print(" ")
	print(" ")
	print("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+")
	print("    |            .          .                `       .        |")
	print("    |          `         *                    ,     .         |")
	print("    |    o             .     `          *                     |")
	print("    |            .          .                `       .        |")
	print("    |      o          .               *                       |")
	print("    |                         .       `                 .     |")
	print("    |         (•_•)                                           |")
	print("    |        <)   )>  GAMEDAY `             *             .   |")
	print("    |     .  /    \                 *                .        |")
	print("    |                         *              o                |")
	print("    | *   .               `             *             .       |")
	print("    +---------------------------------------------------------+")
	print("    ", 10 - i, " more cylces")

	time.sleep(.900)
	
	os.system('cls')
	print(" ")
	print(" ")
	print("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+")
	print("    | *   .               `             *             .       |")
	print("    |            .          .                `       .        |")
	print("    |          `         *                    ,     .         |")
	print("    |    o             .     `          *                     |")
	print("    |            .          .                `       .        |")
	print("    |                         .       `                 .     |")
	print("    |      o  (•_•)                 .             .           |")
	print("    |        <)   )>  GAMEDAY                                 |")
	print("    |        /    \          `             *               .  |")
	print("    |     .                    *        *     o         .     |")
	print("    |      o          .               *                       |")
	print("    +---------------------------------------------------------+")	
	print("    ", 10 - i, " more cylces")
	
	time.sleep(.800)