rm(list=ls())           # R's equivalent to Stata's clear all
cat("\014\n")             # Alternate R equiv to Stata's cls

for(i in 1:10) {
  cat("\014\n")
  cat(" \n")
  cat(" \n")
  cat("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+\n")
  cat("    |    o             .     `          *                     |\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |      o          .               *                       |\n")
  cat("    |           .             .       `                 .     |\n")
  cat("    |        .          o                .         *          |\n")
  cat("    |*              o                                         |\n")
  cat("    |     .   (•_•)/      `             *             .       |\n")
  cat("    |        <)   )   IT'S                                    |\n")
  cat("    |    .   /    |            *                          .   |\n")
  cat("    |    o             .     `          *                     |\n")
  cat("    |            .          .                `       .        |\n")
  cat("    +---------------------------------------------------------+\n")
  cat("        ", 10-i," more cylces\n")

  Sys.sleep(.9)
  
  cat("\014\n")
  cat(" \n")
  cat(" \n")
  cat("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |    o             .     `          *                     |\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |      o          .               *                       |\n")
  cat("    |           .             .       `                 .     |\n")
  cat("    |        .          o                .         *          |\n")
  cat("    |         (•_•)/                                          |\n")
  cat("    |     .  <)   )   IT'S `               *            .     |\n")
  cat("    |        /    |                                           |\n")
  cat("    |    o             .     `   *                       .    |\n")
  cat("    |*              o                    *                    |\n")
  cat("    +---------------------------------------------------------+\n")
  cat("        ", 10-i," more cylces\n")
  
  Sys.sleep(.8)
  
  cat("\014\n")
  cat(" \n")
  cat(" \n")
  cat("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+\n")
  cat("    |           `         *                    ,     .        |\n")
  cat("    |     o             .     `          *                    |\n")
  cat("    |             .          .                `       .       |\n")
  cat("    |       o          .               *                      |\n")
  cat("    |            .             .       `                 .    |\n")
  cat("    |       .            o                .         *         |\n")
  cat("    |         |(•_•)      `             *             .       |\n")
  cat("    |  *   .  (   (>  #BADGERS         *                .     |\n")
  cat("    |         /    |                                          |\n")
  cat("    |       o          .               *                      |\n")
  cat("    |            .             .       `                 .    |\n")
  cat("    +---------------------------------------------------------+\n")
  cat("        ", 10-i," more cylces\n")
  
  Sys.sleep(.9)
  
  cat("\014\n")
  cat(" \n")
  cat(" \n")
  cat("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+\n")
  cat("    |            .             .       `                 .    |\n")
  cat("    |           `         *                    ,     .        |\n")
  cat("    |     o             .     `          *                    |\n")
  cat("    |             .          .                `       .       |\n")
  cat("    |       o          .               *                      |\n")
  cat("    |            .             .       `                 .    |\n")
  cat("    |         |(•_•)                                          |\n")
  cat("    |         (   (>  #BADGERS          *            .        |\n")
  cat("    |    .    /    |        `          *                  .   |\n")
  cat("    | *     .            o                .         *         |\n")	
  cat("    |       o          .               *                      |\n")
  cat("    +---------------------------------------------------------+\n")
  cat("        ", 10-i," more cylces\n")
  
  Sys.sleep(.8)
  
  cat("\014\n")
  cat(" \n")
  cat(" \n")
  cat("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |          `         *                    ,     .         |\n")
  cat("    |    o             .     `          *                     |\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |      o          .               *                       |\n")
  cat("    |                         .       `                 .     |\n")
  cat("    |         (•_•)                                           |\n")
  cat("    |        <)   )>  GAMEDAY `             *             .   |\n")
  cat("    |     .  /    |                 *                .        |\n")
  cat("    |                         *              o                |\n")
  cat("    | *   .               `             *             .       |\n")
  cat("    +---------------------------------------------------------+\n")
  cat("        ", 10-i," more cylces\n")
  
  Sys.sleep(.9)
  
  cat("\014\n")
  cat(" \n")
  cat(" \n")
  cat("    +------ U N I V E R S I T Y  O F  W I S C O N S I N ------+\n")
  cat("    | *   .               `             *             .       |\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |          `         *                    ,     .         |\n")
  cat("    |    o             .     `          *                     |\n")
  cat("    |            .          .                `       .        |\n")
  cat("    |                         .       `                 .     |\n")
  cat("    |      o  (•_•)                 .             .           |\n")
  cat("    |        <)   )>  GAMEDAY                                 |\n")
  cat("    |        /    |          `             *               .  |\n")
  cat("    |     .                    *        *     o         .     |\n")
  cat("    |      o          .               *                       |\n")
  cat("    +---------------------------------------------------------+\n")	
  cat("        ", 10-i," more cylces\n")
  
  Sys.sleep(.8)
}
